services:
  db:
    image: postgres:15
    container_name: agendamento_db
    restart: always
    environment:
      POSTGRES_USER: kamilly
      POSTGRES_PASSWORD: kamillykkk123
      POSTGRES_DB: agendamento_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: